apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mi97renbc-dotnet-basic
  janus-idp.io/tekton: mi97renbc-dotnet-basic
  backstage.io/kubernetes-id: mi97renbc-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mi97renbc-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
