apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mi97renbc-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mi97renbc-dotnet-basic-gitops